// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edvikbiytgtulgxptqid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdmlrYml5dGd0dWxneHB0cWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTM5MTcsImV4cCI6MjA2MzE4OTkxN30.0BuZElwIHF_jRrSXt3H5uBvHtQwZ_WuE3oH3DyNeIM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});